apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: library-app-autoscaler
  namespace: moneeda-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: library-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
        - type: Percent
          value: 10
          periodSeconds: 30
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
        - type: Percent
          value: 10
          periodSeconds: 10
      selectPolicy: Max
